name = "pactsol-tally-notifications"
main = "pactsol-tally-notifications.js"
compatibility_date = "2026-08-25"

[[d1_databases]]
binding = "PACTSOL_DB"
database_name = "pactsol-operations-prod"
database_id = "b9a38a1c-53df-4c63-971f-fee99cbd1b90"
